server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    include /etc/nginx/mime.types;
    charset utf-8;
    charset_types text/vcard;

    location = /cartao/rodrigo.vcf {
        types { text/vcard vcf; }
        default_type text/vcard;
        add_header Content-Disposition 'inline; filename="Dr-Rodrigo.vcf"' always;
        add_header Cache-Control 'no-cache' always;
        add_header X-Content-Type-Options 'nosniff' always;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }
}
